/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import koneksi.koneksi;

public class inputjadwal extends javax.swing.JPanel {

    public inputjadwal() {
        initComponents();

        inputjurusan();
        tampilKelas();
        tampilMapel();
        dataguru();
        tampilRuangan();
    }

    private void bersih(){

    txtHari.setText("");
    txtJam.setText("");
    txtket.setText("");

    if(cmbJurusan.getItemCount() > 0)
        cmbJurusan.setSelectedIndex(0);

    if(cmbKelas.getItemCount() > 0)
        cmbKelas.setSelectedIndex(0);

    if(cmbMapel.getItemCount() > 0)
        cmbMapel.setSelectedIndex(0);

    if(cmbGuru.getItemCount() > 0)
        cmbGuru.setSelectedIndex(0);

    if(cmbRuangan.getItemCount() > 0)
        cmbRuangan.setSelectedIndex(0);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnhome = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbJurusan = new javax.swing.JComboBox<>();
        cmbKelas = new javax.swing.JComboBox<>();
        cmbRuangan = new javax.swing.JComboBox<>();
        cmbMapel = new javax.swing.JComboBox<>();
        cmbGuru = new javax.swing.JComboBox<>();
        txtHari = new javax.swing.JTextField();
        txtJam = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtket = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnDataJadwal = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("INPUT JADWAL PELAJARAN");

        btnhome.setText("Home");
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137)
                .addComponent(btnhome)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnhome))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jLabel2.setText("Jurusan :");

        jLabel3.setText("Kelas :");

        jLabel4.setText("Hari :");

        jLabel5.setText("Jam :");

        jLabel6.setText("Mata Pelajaran :");

        jLabel7.setText("Guru :");

        jLabel8.setText("Ruangan :");

        jLabel9.setText("Keterangan :");

        cmbJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJurusanActionPerformed(evt);
            }
        });

        cmbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKelasActionPerformed(evt);
            }
        });

        cmbRuangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRuanganActionPerformed(evt);
            }
        });

        cmbMapel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMapelActionPerformed(evt);
            }
        });

        cmbGuru.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGuruActionPerformed(evt);
            }
        });

        txtket.setColumns(20);
        txtket.setRows(5);
        jScrollPane1.setViewportView(txtket);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnDataJadwal.setText("Data Jadwal");
        btnDataJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataJadwalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(btnSimpan))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(61, 61, 61)
                                                    .addComponent(cmbJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel6))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel5))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtHari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cmbKelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(137, 137, 137)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))))))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnReset)
                                    .addComponent(jLabel10))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(45, 45, 45)
                        .addComponent(btnDataJadwal)
                        .addGap(52, 52, 52)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(cmbJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(btnDataJadwal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cmbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(cmbRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan)
                            .addComponent(btnReset)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRuanganActionPerformed


    try{

        Connection con = koneksi.getConnection();
        Statement st = con.createStatement();

        ResultSet rs =
        st.executeQuery("SELECT nama_ruangan FROM ruangan");

        cmbRuangan.removeAllItems();

        while(rs.next()){

            cmbRuangan.addItem(
                    rs.getString("nama_ruangan"));

        }

    }catch(Exception e){

        JOptionPane.showMessageDialog(null,e);

    }
    }//GEN-LAST:event_cmbRuanganActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        dashboard form = new dashboard();  
    form.setVisible(true);

    java.awt.Window window =
        javax.swing.SwingUtilities.getWindowAncestor(this);

    if(window != null){
    window.dispose();
}
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    try{
        System.out.println("Jurusan  : " + cmbJurusan.getSelectedItem());
System.out.println("Kelas    : " + cmbKelas.getSelectedItem());
System.out.println("Mapel    : " + cmbMapel.getSelectedItem());
System.out.println("Guru     : " + cmbGuru.getSelectedItem());
System.out.println("Ruangan  : " + cmbRuangan.getSelectedItem());
        String sql =
        "INSERT INTO jadwal(jurusan,kelas,mapel,guru,ruangan,hari,jam,keterangan)"
        + " VALUES('"
        + cmbJurusan.getSelectedItem().toString() + "','"
        + cmbKelas.getSelectedItem().toString() + "','"
        + cmbMapel.getSelectedItem().toString() + "','"
        + cmbGuru.getSelectedItem().toString() + "','"
        + cmbRuangan.getSelectedItem().toString() + "','"
        + txtHari.getText() + "','"
        + txtJam.getText() + "','"
        + txtket.getText() + "')";
        
        System.out.println(sql);

        Connection con = koneksi.getConnection();
        Statement st = con.createStatement();

        st.executeUpdate(sql);

        JOptionPane.showMessageDialog(
                null,
                "Data Jadwal Berhasil Disimpan");

        bersih();

    }catch(Exception e){

    e.printStackTrace();

    JOptionPane.showMessageDialog(
            null,
            e);

}

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void cmbKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKelasActionPerformed

    try{

        Connection con = koneksi.getConnection();
        Statement st = con.createStatement();

        ResultSet rs =
        st.executeQuery("SELECT nama_kelas FROM kelas");

        cmbKelas.removeAllItems();

        while(rs.next()){

            cmbKelas.addItem(
                    rs.getString("nama_kelas"));

        }

    }catch(Exception e){

        JOptionPane.showMessageDialog(null,e);

    }

}

   private void dataguru(){

    try{

        Connection con = koneksi.getConnection();
        Statement st = con.createStatement();

        ResultSet rs =
        st.executeQuery("SELECT nama_guru FROM guru");

        cmbGuru.removeAllItems();

        while(rs.next()){

            cmbGuru.addItem(
                    rs.getString("nama_guru"));

        }

    }catch(Exception e){

        JOptionPane.showMessageDialog(null,e);

    }

}

    private void tampilMapel(){

    try{

        Connection con = koneksi.getConnection();
        Statement st = con.createStatement();

        ResultSet rs =
        st.executeQuery("SELECT nama_mapel FROM mapel");

        cmbMapel.removeAllItems();

        while(rs.next()){

            cmbMapel.addItem(
                    rs.getString("nama_mapel"));

        }

    }catch(Exception e){

        JOptionPane.showMessageDialog(null,e);

    }

}

    private void tampilKelas() {

    try{

        Connection con = koneksi.getConnection();
        Statement st = con.createStatement();

        ResultSet rs =
        st.executeQuery("SELECT nama_kelas FROM kelas");

        cmbKelas.removeAllItems();

        while(rs.next()){

            cmbKelas.addItem(
                    rs.getString("nama_kelas"));

        }

    }catch(Exception e){

        JOptionPane.showMessageDialog(null,e);

    }

}

    private void inputjurusan() {

    try{

        Connection con = koneksi.getConnection();
        Statement st = con.createStatement();

        ResultSet rs =
        st.executeQuery("SELECT nama_jurusan FROM jurusan");

        cmbJurusan.removeAllItems();

        while(rs.next()){

            cmbJurusan.addItem(
                    rs.getString("nama_jurusan"));

        }

    }catch(Exception e){

        JOptionPane.showMessageDialog(null,e);

    }

    }

    private void tampilRuangan(){

    try{

        Connection con = koneksi.getConnection();
        Statement st = con.createStatement();

        ResultSet rs =
        st.executeQuery("SELECT nama_ruangan FROM ruangan");

        cmbRuangan.removeAllItems();

        while(rs.next()){

            cmbRuangan.addItem(
                    rs.getString("nama_ruangan"));

        }

    }catch(Exception e){

        JOptionPane.showMessageDialog(null,e);

    }




    }//GEN-LAST:event_cmbKelasActionPerformed

    private void cmbJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJurusanActionPerformed

    }//GEN-LAST:event_cmbJurusanActionPerformed

    private void cmbMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMapelActionPerformed
   
    }//GEN-LAST:event_cmbMapelActionPerformed

    private void cmbGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGuruActionPerformed

    }//GEN-LAST:event_cmbGuruActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
    bersih();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnDataJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataJadwalActionPerformed


    javax.swing.JFrame frame = new javax.swing.JFrame("Data Jadwal");

    frame.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    frame.setContentPane(new jadwal());
    frame.pack();
    frame.setLocationRelativeTo(null);
    frame.setVisible(true);

    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window != null) {
        window.dispose();
    }
    }//GEN-LAST:event_btnDataJadwalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDataJadwal;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnhome;
    private javax.swing.JComboBox<String> cmbGuru;
    private javax.swing.JComboBox<String> cmbJurusan;
    private javax.swing.JComboBox<String> cmbKelas;
    private javax.swing.JComboBox<String> cmbMapel;
    private javax.swing.JComboBox<String> cmbRuangan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtHari;
    private javax.swing.JTextField txtJam;
    private javax.swing.JTextArea txtket;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
